workflows:
  native-android:
    name: Android
    environment:
      xcode: 16.3
      ndk: 28.0.13004108
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - helina@neverode.io
        notify:
          success: true
          failure: false
  test_linux:
    name: Linux test workflow
    instance_type: linux_x2
    environment:
      ubuntu: 24.04
      ndk: 28.0.13004108
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - helina@neverode.io
        notify:
          success: true
          failure: false
  test_m1:
    name: Deprecated M1 workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - helina@neverode.io
        notify:
          success: true
          failure: false
  
