workflows:
  native-android:
    name: Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/**.apk
    publishing:
      email:
        recipients:
          - helina@neverode.io
        notify:
          success: true
          failure: false
